# Generated by Django 4.2.1 on 2023-05-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='details',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='details',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
