# Generated by Django 4.2.1 on 2023-05-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0002_rename_detail_id_assigned_resource_id'),
        ('resource', '0002_remove_details_cost_remove_details_start_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Resource',
        ),
    ]
